keymap:"3l"
partition{
 - " M"
 - " M"
 - ""
}
format{
 - "fat32"
 - "ext4"
}
mount{
 - "/mnt/boot/efi"
 - "/mnt"
}
custom commands{
 - "(NULL)"
 - "(NULL)"
 - "(NULL)"
 - "(NULL)"
}
applications:"base linux linux-firmware sof-firmware base-devel grub efibootmgr"
grub:"truez"